<?php
/** @var Magenest\Junior\Block\Product\View $block */
$cookieName = \Magenest\Junior\Helper\Cookie::COOKIE_NAME;
?>
<div class="gift-card">
    <fieldset>
        <legend><?= __("GIFT CARD") ?></legend>
        <div id="gift-card-form">
            <form id="frm-gift-card" data-mage-init='{"validation": {}}'>
                <div class="field required">
                    <label for="receiver_name"><?= __("Receiver name") ?></label>
                    <input type="text"
                           class="receiver_name"
                           id="receiver_name"
                           name="receiver_name"
                           data-validate="{required:true, 'validate-receiver-name': true}"
                    />
                </div>
                <div class="field required">
                    <label for="receiver_message"><?= __("Message") ?></label>
                    <textarea class="receiver_message" name="receiver_message" id="receiver_message"
                              data-validate="{required:true, 'validate-receiver-message': true}"></textarea>
                </div>
                <button class="action primary" id="btn-save" type="button"><?=__("Save Message")?></button>
            </form>
        </div>
        <div id="gift-card-view" hidden="hidden">
            <label class="gift-card-view-label"><?= __("Receiver name") ?>: </label> <span
                    id="view_receiver_name"></span><br>
            <label class="gift-card-view-label"><?= __("Message") ?>: </label> <span id="view_receiver_message"></span><br>
            <button class="action primary" id="gift-card-view-edit"><?=__("Edit");?></button>
        </div>
        <a  id="btn-delete"><?=__("Clear"); ?></a>
    </fieldset>
</div>


<script>
    require(['jquery', 'mage/validation'],
        function ($) {
            $.validator.addMethod(
                'validate-receiver-name', function (value) {
                    return value.length < 100;
                }, $.mage.__("Please input maximum 100 characters in this field")
            );
            $.validator.addMethod(
                'validate-receiver-message', function (value) {
                    return value.length < 1000;
                }, $.mage.__("Please input maximum 1000 characters in this field")
            );
        });
</script>
<script type="text/x-magento-init">
{
    "*": {
        "view": {
            "submitUrl": "<?= $block->getUrl('junior/ajax_giftcard/save'); ?>",
            "deleteUrl": "<?= $block->getUrl('junior/ajax_giftcard/delete'); ?>",
            "cookieName": "<?= $cookieName; ?>"
        }
    }
}


</script>
<style>
    .gift-card-view-label {
        font-weight: bold;
    }
</style>